src/Entity/Application.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ApplicationRepository")
 */
class Application
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $app_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $app_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientUsesApplication", mappedBy="application")
     */
    private $clientUsesApplications;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientApplicationsConfiguration", mappedBy="application")
     */
    private $clientApplicationsConfigurations;

    public function __construct()
    {
        $this->clientUsesApplications = new ArrayCollection();
        $this->clientApplicationsConfigurations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAppId(): ?int
    {
        return $this->app_id;
    }

    public function setAppId(int $app_id): self
    {
        $this->app_id = $app_id;

        return $this;
    }

    public function getAppName(): ?string
    {
        return $this->app_name;
    }

    public function setAppName(string $app_name): self
    {
        $this->app_name = $app_name;

        return $this;
    }

    /**
     * @return Collection|ClientUsesApplication[]
     */
    public function getClientUsesApplications(): Collection
    {
        return $this->clientUsesApplications;
    }

    public function addClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if (!$this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications[] = $clientUsesApplication;
            $clientUsesApplication->setApplication($this);
        }

        return $this;
    }

    public function removeClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if ($this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications->removeElement($clientUsesApplication);
            // set the owning side to null (unless already changed)
            if ($clientUsesApplication->getApplication() === $this) {
                $clientUsesApplication->setApplication(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ClientApplicationsConfiguration[]
     */
    public function getClientApplicationsConfigurations(): Collection
    {
        return $this->clientApplicationsConfigurations;
    }

    public function addClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if (!$this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations[] = $clientApplicationsConfiguration;
            $clientApplicationsConfiguration->setApplication($this);
        }

        return $this;
    }

    public function removeClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if ($this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations->removeElement($clientApplicationsConfiguration);
            // set the owning side to null (unless already changed)
            if ($clientApplicationsConfiguration->getApplication() === $this) {
                $clientApplicationsConfiguration->setApplication(null);
            }
        }

        return $this;
    }
}

src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientApplicationsConfiguration", mappedBy="category")
     */
    private $clientApplicationsConfigurations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientCategoryConfiguration", mappedBy="category", orphanRemoval=true)
     */
    private $clientCategoryConfigurations;

    public function __construct(string $name)
    {
        $this->clientApplicationsConfigurations = new ArrayCollection();
        $this->clientCategoryConfigurations = new ArrayCollection();
        $this->category_name = $name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCategoryName(): ?string
    {
        return $this->category_name;
    }

    public function setCategoryName(string $category_name): self
    {
        $this->category_name = $category_name;

        return $this;
    }

    /**
     * @return Collection|ClientApplicationsConfiguration[]
     */
    public function getClientApplicationsConfigurations(): Collection
    {
        return $this->clientApplicationsConfigurations;
    }

    public function addClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if (!$this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations[] = $clientApplicationsConfiguration;
            $clientApplicationsConfiguration->setCategory($this);
        }

        return $this;
    }

    public function removeClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if ($this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations->removeElement($clientApplicationsConfiguration);
            // set the owning side to null (unless already changed)
            if ($clientApplicationsConfiguration->getCategory() === $this) {
                $clientApplicationsConfiguration->setCategory(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ClientCategoryConfiguration[]
     */
    public function getClientCategoryConfigurations(): Collection
    {
        return $this->clientCategoryConfigurations;
    }

    public function addClientCategoryConfiguration(ClientCategoryConfiguration $clientCategoryConfiguration): self
    {
        if (!$this->clientCategoryConfigurations->contains($clientCategoryConfiguration)) {
            $this->clientCategoryConfigurations[] = $clientCategoryConfiguration;
            $clientCategoryConfiguration->setCategory($this);
        }

        return $this;
    }

    public function removeClientCategoryConfiguration(ClientCategoryConfiguration $clientCategoryConfiguration): self
    {
        if ($this->clientCategoryConfigurations->contains($clientCategoryConfiguration)) {
            $this->clientCategoryConfigurations->removeElement($clientCategoryConfiguration);
            // set the owning side to null (unless already changed)
            if ($clientCategoryConfiguration->getCategory() === $this) {
                $clientCategoryConfiguration->setCategory(null);
            }
        }

        return $this;
    }

}

src/Entity/ProductivityLevel.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductivityLevelRepository")
 */
class ProductivityLevel
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $level_name;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Category", mappedBy="productivity_level")
     */
    private $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientCategoryConfiguration", mappedBy="productivityLevel", orphanRemoval=true)
     */
    private $clientCategoryConfigurations;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->clientCategoryConfigurations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLevelName(): ?string
    {
        return $this->level_name;
    }

    public function setLevelName(string $level_name): self
    {
        $this->level_name = $level_name;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
            $category->setProductivityLevel($this);
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        if ($this->categories->contains($category)) {
            $this->categories->removeElement($category);
            // set the owning side to null (unless already changed)
            if ($category->getProductivityLevel() === $this) {
                $category->setProductivityLevel(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ClientCategoryConfiguration[]
     */
    public function getClientCategoryConfigurations(): Collection
    {
        return $this->clientCategoryConfigurations;
    }

    public function addClientCategoryConfiguration(ClientCategoryConfiguration $clientCategoryConfiguration): self
    {
        if (!$this->clientCategoryConfigurations->contains($clientCategoryConfiguration)) {
            $this->clientCategoryConfigurations[] = $clientCategoryConfiguration;
            $clientCategoryConfiguration->setProductivityLevel($this);
        }

        return $this;
    }

    public function removeClientCategoryConfiguration(ClientCategoryConfiguration $clientCategoryConfiguration): self
    {
        if ($this->clientCategoryConfigurations->contains($clientCategoryConfiguration)) {
            $this->clientCategoryConfigurations->removeElement($clientCategoryConfiguration);
            // set the owning side to null (unless already changed)
            if ($clientCategoryConfiguration->getProductivityLevel() === $this) {
                $clientCategoryConfiguration->setProductivityLevel(null);
            }
        }

        return $this;
    }
}

src/Controller/CategoriesConfigurationController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\EventManager;
use App\Entity\Client;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Application;
use App\Entity\ClientCategoryConfiguration;
use App\Entity\ClientApplicationsConfiguration;
use App\Entity\ProductivityLevel;
use App\Entity\Category;

class CategoriesConfigurationController extends AbstractController
{
    /**
     * @Route("/categories/configuration/{page}", name="categories_configuration", defaults={"page"=1})
     */
    public function index($page)
    {
    	$entityManager = $this->getDoctrine()->getManager();

        $clientId = $this->get('security.token_storage')->getToken()->getUser()->getId();
        $pageLimit = 5;

        //$countFilters = array('client' => $clientId);
        $countFilters = array();
        $appConfigurations = $this->getDoctrine()->getRepository(ClientApplicationsConfiguration::class)->findBy(array('client' => $clientId));

        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        $levels = $this->getDoctrine()->getRepository(ProductivityLevel::class)->findAll();

        $applicationsCount = sizeof($appConfigurations);
        $totalPages = ceil($applicationsCount / $pageLimit);

        $appConfigurations = $this->getDoctrine()->getRepository(ClientApplicationsConfiguration::class)->findBy(array('client' => $clientId), null, $pageLimit, ($page - 1) * $pageLimit);

        return $this->render('categories_configuration/index.html.twig', [
            'controller_name' => 'CategoriesConfigurationController', 
            	'appConfigurations' => $appConfigurations , 
            	'totalPages' => $totalPages , 
            	'currentPage' => $page ,
                'categories' => $categories ,
                'levels' => $levels
        ]);
    }


    /**
     * 
     * @Route("/{app}/{category}/change-category", name="change_category_route")
     * @return RedirectResponse
     *
     */
    public function changeAppCategory(String $app, String $category){

        $entityManager = $this->getDoctrine()->getManager();

        /* Recuperar la configuracion cliente/aplicacion */
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clientId = $client->getId();
        $application = $this->getDoctrine()->getRepository(Application::class)->findOneBy(array('app_name' => $app));
        $appId = $application->getId();
        $categoryOb = $this->getDoctrine()->getRepository(Category::class)->findOneBy(array('category_name' => $category));

        $appConfiguration = $this->getDoctrine()->getRepository(ClientApplicationsConfiguration::class)->findOneBy(array('client' => $clientId,'application' => $appId));

        /* Cambiar la configuracion para que tenga la categoria recibida */
        
        $appConfiguration->setCategory($categoryOb);


        /* Persistir */
        $entityManager->persist($appConfiguration);
        $entityManager->flush();






        return $this->redirectToRoute('categories_configuration');
    }



    /**
     * 
     * @Route("/{appName}/{level}/change-level", name="change_category_level_route")
     * @return RedirectResponse
     *
     */
    public function changeCategoryLevel(String $appName, String $level){

        $entityManager = $this->getDoctrine()->getManager();

        /* Recuperar la configuracion de categorias del cliente */
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clientId = $client->getId();
        
        /* Tengo el appName, necesito recuperar su categoria */
        $application = $this->getDoctrine()->getRepository(Application::class)->findOneBy(array('app_name' => $appName));
        $appId = $application->getId();
        $appConfiguration = $this->getDoctrine()->getRepository(ClientApplicationsConfiguration::class)->findOneBy(array('client' => $clientId,'application' => $appId));
        $category= $appConfiguration->getCategory();
        $categoryId = $category->getId();
        /* FIN RECUPERANDO CATEGORIA */
     

        $level = $this->getDoctrine()->getRepository(ProductivityLevel::class)->findOneBy(array('level_name' => $level));

        $categoryConfiguration = $this->getDoctrine()->getRepository(ClientCategoryConfiguration::class)->findOneBy(array('client' => $clientId,'category' => $categoryId));

        /* Cambiar la configuracion para que tenga el nivel recibido */
        
        $categoryConfiguration->setProductivityLevel($level);


        /* Persistir */
        $entityManager->persist($categoryConfiguration);
        $entityManager->flush();






        return $this->redirectToRoute('categories_configuration');
    }
}

templates/categories_configuration/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Configuración de aplicaciones y categorías {{ controller_name }}{% endblock %}

{% block body %}

	<div class="container my-tasks-form-container d-flex justify-content-center align-items-center">
		<div class="row">
			<div class="position-relative shadow bg-white border-top col-md-12 my-tasks-box">
				<h2 class="text-center font-weight-light">Configuraciones de categorías y aplicaciones</h2>
				<br>
				{% if appConfigurations is defined %}
                    <div  class="my-tasks-task-section">
                        {% for appConfiguration in appConfigurations %}
                        	
                            <div class="my-tasks-task-container my-3">
	                            <span class="my-tasks-task-name" title="{{ appConfiguration.application.appName }}">
	                            	{{ appConfiguration.application.appName }}
	                            </span>

	                            <select title="Cambiar la categoria de {{appConfiguration.application.appName}}" class="custom-select my-tasks-select-sort" onchange="javascript:seleccionarCategoria('{{appConfiguration.application.appName}}', this)" id="select-category">

		                          	<option selected disabled hidden >
		                            	{{ appConfiguration.category.categoryName }}
		                        	</option>
		                        	{% for category in categories %}
			                        	<option >
			                            	{{ category.categoryName }}
			                        	</option>
		                        	{% endfor %}
	                    		</select>

	                    		<select title="Cambiar el nivel de productividad de {{ appConfiguration.category.getCategoryName() }}" class="custom-select my-tasks-select-sort" onchange="javascript:seleccionarNivel('{{appConfiguration.application.appName}}', this)" id="select-category">
		                          	<option selected disabled hidden >
		                            	{{ app.user.productivityLevelFor(appConfiguration.category) }}
		                        	</option>
		                        	{% for level in levels %}
			                        	<option >
			                            	{{ level.levelName }}
			                        	</option>
		                        	{% endfor %}
		                        	
	                    		</select>


	                    		<script type="text/javascript">
								function seleccionarCategoria(appName,categoria)
									{
										window.location = '/'+appName+'/'+categoria.value+'/change-category';
									}

								function seleccionarNivel(appName,nivel)
									{																
										window.location = '/'+appName+'/'+nivel.value+'/change-level';
									}
								</script>

                    		</div>                              
                        {% endfor %}
                    </div>

                {% endif %}
                {% if totalPages > 0 %}
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if currentPage == 1 %} disabled {% endif %}">
                            <a class="page-link"
                               href="{{ path('categories_configuration', {'page': currentPage-1}) }}">Anterior</a>
                        </li>
                        {% for i in 1..totalPages %}
                            <li class="page-item {% if currentPage == i %} active {% endif %}">
                                <a class="page-link"
                                   href="{{ path('categories_configuration', {'page': i}) }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        <li class="page-item  {% if currentPage == totalPages %} disabled {% endif %}">
                            <a class="page-link"
                               href="{{ path('categories_configuration', {'page': currentPage+1}) }}">Siguiente</a>
                        </li>
                    </ul>
                {% endif %}
			</div>
		</div>
	</div>

{% endblock %}