src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 * @ORM\AttributeOverrides({
 *      @ORM\AttributeOverride(name="email",
 *          column=@ORM\Column(
 *              name     = "email",
 *              length   = 191,
 *              unique   = true
 *          )
 *      )
 * })
 * @UniqueEntity(fields={"email"}, message="Ya existe un usuario con ese email.")
 */

class Client implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer", unique=true)
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $secret_answer;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\SecretQuestion", inversedBy="clients")
     */
    private $secret_question;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ReportFrequency", inversedBy="clients")
     */
    private $report_frequency;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\PomodorosConfiguration", cascade={"persist", "remove"})
     */
    private $pomodoros_configuration;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Task", mappedBy="client")
     */
    private $tasks;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientUsesApplication", mappedBy="client")
     */
    private $clientUsesApplications;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Clock", mappedBy="client", cascade={"persist", "remove"})
     */
    private $clock;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientApplicationsConfiguration", mappedBy="client")
     */
    private $clientApplicationsConfigurations;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientCategoryConfiguration", mappedBy="client", orphanRemoval=true)
     */
    private $clientCategoryConfigurations;

    public function __construct()
    {
        $this->tasks = new ArrayCollection();
        $this->clientUsesApplications = new ArrayCollection();
        $this->clientApplicationsConfigurations = new ArrayCollection();
        $this->clientCategoryConfigurations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

  public function getUsername(): ?string
    {
        return $this->email;
    }

    public function setUsername(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

     public function getRoles()
        {
            return array('ROLE_USER');
        }

    public function eraseCredentials()
    {
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->first_name,
            $this->last_name,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            $this->first_name,
            $this->last_name,
        ) = unserialize($serialized, array('allowed_classes' => false));
    }

    public function getSecretAnswer(): ?string
    {
        return $this->secret_answer;
    }

    public function setSecretAnswer(string $secret_answer): self
    {
        $this->secret_answer = $secret_answer;

        return $this;
    }

    public function getSecretQuestion(): ?SecretQuestion
    {
        return $this->secret_question;
    }

    public function setSecretQuestion(?SecretQuestion $secret_question): self
    {
        $this->secret_question = $secret_question;

        return $this;
    }

    public function getReportFrequency(): ?ReportFrequency
    {
        return $this->report_frequency;
    }

    public function setReportFrequency(?ReportFrequency $report_frequency): self
    {
        $this->report_frequency = $report_frequency;

        return $this;
    }

    public function getPomodorosConfiguration(): ?PomodorosConfiguration
    {
        return $this->pomodoros_configuration;
    }

    public function setPomodorosConfiguration(?PomodorosConfiguration $pomodoros_configuration): self
    {
        $this->pomodoros_configuration = $pomodoros_configuration;

        return $this;
    }

    /**
     * @return Collection|Task[]
     */
    public function getTasks(): Collection
    {
        return $this->tasks;
    }

    public function addTask(Task $task): self
    {
        if (!$this->tasks->contains($task)) {
            $this->tasks[] = $task;
            $task->setClient($this);
        }

        return $this;
    }

    public function removeTask(Task $task): self
    {
        if ($this->tasks->contains($task)) {
            $this->tasks->removeElement($task);
            // set the owning side to null (unless already changed)
            if ($task->getClient() === $this) {
                $task->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|ClientUsesApplication[]
     */
    public function getClientUsesApplications(): Collection
    {
        return $this->clientUsesApplications;
    }

    public function addClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if (!$this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications[] = $clientUsesApplication;
            $clientUsesApplication->setClient($this);
        }

        return $this;
    }

    public function removeClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if ($this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications->removeElement($clientUsesApplication);
            // set the owning side to null (unless already changed)
            if ($clientUsesApplication->getClient() === $this) {
                $clientUsesApplication->setClient(null);
            }
        }

        return $this;
    }

    public function getClock(): ?Clock
    {
        return $this->clock;
    }

    public function setClock(Clock $clock): self
    {
        $this->clock = $clock;

        // set the owning side of the relation if necessary
        if ($this !== $clock->getClient()) {
            $clock->setClient($this);
        }

        return $this;
    }

    public function canShowClock(): bool
    {
        //Lo puede mostrar si no es null
        return !(is_null($this->clock));
    }

    public function canStartTask(): bool
    {
        //el usuario puede iniciar tareas solo si no hay una en curso
        return is_null($this->clock);
    }

    public function canStopTask(): bool
    {
        return !(is_null($this->clock));
    }

    public function canFinishTask(): bool
    {
        return !(is_null($this->clock));
    }
    public function stopTask(TaskState $state): self
    {
        //Cambiar el state de la tarea
        $this->clock->stop($state);

        //Destruir el reloj
        unset($this->clock);

        return $this;
    }

    public function startClockForTask(Task $task): self
    {
        //Cambiar el state de la tarea a activo viene a ser responsabilidad de la funcion que llama a esta.
        
        $this->setClock(new Clock($this, $task));
      
        return $this;
    }

    /**
     * @return Collection|ClientApplicationsConfiguration[]
     */
    public function getClientApplicationsConfigurations(): Collection
    {
        return $this->clientApplicationsConfigurations;
    }

    public function addClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if (!$this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations[] = $clientApplicationsConfiguration;
            $clientApplicationsConfiguration->setClient($this);
        }

        return $this;
    }

    public function removeClientApplicationsConfiguration(ClientApplicationsConfiguration $clientApplicationsConfiguration): self
    {
        if ($this->clientApplicationsConfigurations->contains($clientApplicationsConfiguration)) {
            $this->clientApplicationsConfigurations->removeElement($clientApplicationsConfiguration);

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1" name="viewport" />

    <title>{% block title %} Mi tiempo y mis tomates - Métodos Ágiles para Aplicaciones Web 2018{% endblock %}</title>
    {% block stylesheets %}
        <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900'
              rel='stylesheet' type='text/css'>
        <script src="https://code.highcharts.com/highcharts.js"></script>
        <link rel="stylesheet" href="{{ asset('build/app.css') }}">
    {% endblock %}
</head>
<body>

{% include 'navigation.html.twig' %}
<script src="{{ asset('build/app.js') }}"></script>
</div>
{% for label, messages in app.flashes %}
    {% for message in messages %}
        <div class="text-center alert alert-{{ label }}">
            <strong>{{ message }}</strong>
        </div>
    {% endfor %}
{% endfor %}
{% block body %}
{% endblock %}

{% block javascripts %}
{% endblock %}
</body>
</html>

templates/email_report.html.twig
<!DOCTYPE html>
<html>
<body style="box-sizing:border-box;margin:0;font-family:'Roboto', sans-serif;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff;height:100%;">
<div class="container email-report-container mt-5"
     style="box-sizing:border-box;width:960px;padding-right:15px;padding-left:15px;margin-right:auto;margin-left:auto;max-width:1280px;margin-top:3rem !important;height:100%;">
    <div class="position-relative pt-3 email-report-box"
         style="box-sizing:border-box;position:relative !important;padding-top:1rem !important;height:auto;width:960px;border-radius:10px;">
        <div class="d-flex justify-content-around align-items-baseline mb-4"
             style="box-sizing:border-box;margin-bottom:1.5rem !important; display: inline-block; padding: 20px 80px;">
            <h2 class="font-weight-light pl-5"
                style="box-sizing:border-box;margin-top:0;margin-bottom:0.5rem;font-family:inherit;font-weight:300 !important;line-height:1.2;color:inherit;font-size:2rem;padding-left:3rem !important;">
                Mi Tiempo y Mis Tomates </h2>
            <h5 class="font-weight-light pl-5"
                style="box-sizing:border-box;margin-top:0;margin-bottom:0.5rem;font-family:inherit;font-weight:300 !important;line-height:1.2;color:inherit;font-size:1.25rem;padding-left:3rem !important;">
                Su reporte de uso personalizado</h5>
        </div>

        <div class="align-items-center email-report-pomodoros-box mt-3 w-100 "
             style="box-sizing:border-box;margin-top:1rem !important;align-items:center !important;height:365px;border-radius:80px;border:2px solid #000000;">
            <div class="justify-content-around w-100 mt-3"
                 style="box-sizing:border-box;display: inline-block;width:100% !important;margin-top:1rem !important; padding: 10px 77px;">
                <div class="align-items-center"
                     style="box-sizing:border-box; display: inline-block; height: 60px;">
                    <div style="box-sizing: border-box;"> Esta semana usted realizó</div>
                    <h1 class="my-0"
                        style="box-sizing:border-box;margin-top:0 !important;margin-bottom:0 !important; margin-left: 60px; font-family:inherit;font-weight:500;line-height:1.2;color:inherit;font-size:2.5rem;">
                        {{ tasksData[0] }} </h1>
                    <div style="box-sizing: border-box;margin-left: 44px;"> Pomodoros</div>
                </div>

                <div class="align-items-center"
                     style="box-sizing:border-box; display: inline-block;  position: absolute; left: 650px;">
                    <div style="box-sizing: border-box;"> Estuviste conectado durante</div>
                    <h1 class="my-0"
                        style="box-sizing:border-box;margin-top:0 !important;margin-bottom:0 !important;font-family:inherit;font-weight:500;line-height:1.2;color:inherit;font-size:2.5rem;">
                        {{ connectedTime }}</h1>
                </div>
            </div>

            <div class="mt-5" style="box-sizing:border-box;width: 240px; margin-top: 40px; margin-left: 310px;">
                <ul class="list-unstyled position-relative"
                    style="box-sizing:border-box;margin-top:0;margin-bottom:1rem;padding-left:0;list-style:none;position:relative !important;">

                    {% for task, key in tasksData[1] %}
                        <li class="position-relative mb-2"
                            style="box-sizing:border-box;position:relative !important;margin-bottom:0.5rem !important;">
                            {{ task }}
                            <div class="email-report-pomodoro-count bg-danger position-absolute"
                                 style="box-sizing:border-box;background-color:#dc3545 !important;position:absolute !important;right:-95px;top:3px;width:35px;height:20px;text-align:center;color:#ffffff;border-radius:5px;">
                                {{ key }}
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="justify-content-around mt-5"
         style="box-sizing:border-box;display:flex !important;margin-top:3rem !important;justify-content:space-around !important;">
        <div style="box-sizing: border-box; width: 50%;">
            <div class="font-weight-bold mb-3"
                 style="box-sizing:border-box;margin-bottom:1rem !important;font-weight:700 !important;"> La mayor parte
                de su tiempo la utilizó en:
            </div>
            <ul class="list-unstyled position-relative"
                style="box-sizing:border-box;margin-top:0;margin-bottom:1rem;padding-left:0;list-style:none;position:relative !important;">

                {% for category, percentage in categoriesData %}
                    <div style="box-sizing: border-box;">
                        <div class="email-report-category-percentage d-inline-block mr-4 bg-danger"
                             style="box-sizing:border-box;background-color:#dc3545 !important;margin-right:1.5rem !important;display:inline-block !important;right:-95px;top:3px;width:40px;height:22px;text-align:center;color:#ffffff;border-radius:5px;">
                            {{ percentage }}%
                        </div>
                        <li class="position-relative d-inline-block mb-2"
                            style="box-sizing:border-box;position:relative !important;margin-bottom:0.5rem !important;display:inline-block !important;">
                            {{ category }}
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>
        <div class="email-report-separator-line"
             style="box-sizing:border-box;height:200px;border:1px solid #00000029;"></div>
        <div style="box-sizing: border-box; width: 65%; padding-left: 14%;">
            <div class="font-weight-bold mb-3"
                 style="box-sizing:border-box;margin-bottom:1rem !important;font-weight:700 !important;"> Aplicaciones
                que m&aacute;s utiliz&oacute;:
            </div>
            <ul class="list-unstyled position-relative"
                style="box-sizing:border-box;margin-top:0;margin-bottom:1rem;padding-left:0;list-style:none;!important;position:relative !important;">

                {% for application, duration in appsData %}
                    <div style="box-sizing: border-box;">
                        <div class="email-report-category-percentage d-inline-block mr-4 bg-danger"
                             style="box-sizing:border-box;background-color:#dc3545 !important;margin-right:1.5rem !important;display:inline-block !important;right:-95px;top:3px;width:100px;height:22px;text-align:center;color:#ffffff;border-radius:5px;">
                            {{ duration }} segs
                        </div>
                        <li class="position-relative d-inline-block mb-2"
                            style="box-sizing:border-box;position:relative !important;margin-bottom:0.5rem !important;display:inline-block !important;">
                            {{ application }}
                        </li>
                    </div>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
</body>

templates/home.html.twig
{% extends "base.html.twig" %}

{% block body %}
    <div class="jumbotron">

        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
            <h1 class="display-5">¡Bienvenido a Mi Tiempo y Mis Tomates!</h1>
            <br>
            <p class="lead">Le ayudamos a mejorar su productividad midiendo el tiempo en que usa cada aplicación o página web, además de utilizar la metodología <i>pomodoro</i>.</p>
            <hr class="my-4">

            <p>Para acceder a su cuenta haga <a href="{{ path('login') }}">click aquí</a>, si aún no tiene cuenta, regístrese haciendo <a href="{{ path('user_registration') }}"> click aquí</a>. </p>
        {% endif %}
        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <h1 class="display-5">¡Bienvenido a Mi Tiempo y Mis Tomates {{ app.user.firstName }} {{ app.user.lastName }}!</h1>

            <p class="lead">Le ayudamos a mejorar su productividad midiendo el tiempo en que usa cada aplicación o página web, además de utilizar la metodología <i>pomodoro</i>.</p>
            <hr class="my-4">

            <p>Para esto le proporcionaremos un programa para su ordenador que medirá el uso de las aplicaciones.</p>
            
            <a class="btn btn-primary" href="{{ path('download') }}" role="button">Descargar la aplicación</a>
            <br>
            <br>

            <p>Para comenzar a crear tareas, haga click en el botón.</p>

            <p class="lead">
                <a class="btn btn-primary" href="{{ path('my_tasks') }}" role="button">Ver Mis Tareas</a>
            </p>
        {% endif %}

    </div>
{% endblock %}

templates/navigation.html.twig
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<nav class="navbar navbar-expand-lg navbar-light bg-white shadow">
    <div class="container">

        <a class="navbar-brand text-danger" href="{{ path('home') }}">Mi tiempo y mis tomates</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-black-50" href="{{ path('home') }}"> Inicio <span
                                class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link text-black-50" href="{{ path('download') }}"> <img src="/build/assets/img/buttons/download.png" class="navigation-download-button"> Descargas   <span
                                class="sr-only"></span></a>

                </li>
            </ul>

            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                {% include 'navigation_task/index.html.twig' %}
            {% endif %}

            <ul class="navbar-nav ml-auto">
                {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item active">
                        <a class="nav-link text-black-50" href="{{ path('login') }}"> Iniciar Sesión <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-black-50" href="{{ path('user_registration') }}"> Registrarse <span
                                    class="sr-only">(current)</span></a>
                    </li>
                {% endif %}
                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item active">
                        <a class="nav-link text-black-50" href="{{ path('my_tasks') }}"> Mis Tareas <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link text-black-50" href="{{ path('my_reports_tasks') }}"> Mis Reportes <span class="sr-only">(current)</span></a>
                    </li>
                {% endif %}

                {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-black-50" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Ajustes

                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ path('pomodoro_configuration') }}">Configurar
                                Pomodoros</a>
                            <a class="dropdown-item" href="{{ path('categories_configuration') }}">Configurar
                                Categorías</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown mr-4">
                        <a class="nav-link dropdown-toggle text-black-50" href="#" id="navbarDropdown" role="button"
                           data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {{ app.user.firstName }} {{ app.user.lastName }}

                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{{ path('account_configuration') }}">Mi cuenta</a>
                            <a class="dropdown-item" href="{{ path('logout') }}">Cerrar sesión</a>
                        </div>
                    </li>
                {% endif %}

            </ul>
        </div>
    </div>
</nav>