src/Entity/Task.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TaskRepository")
 */
class Task
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $task_name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="integer")
     */
    private $stimated_pomodoros;

    /**
     * @ORM\Column(type="boolean")
     */
    private $active;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Client", inversedBy="tasks")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TaskState", inversedBy="tasks")
     */
    private $task_state;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Pomodoro", mappedBy="task")
     */
    private $pomodoros;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Clock", mappedBy="task", cascade={"persist", "remove"})
     */
    private $clock;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ClientUsesApplication", mappedBy="task")
     */
    private $clientUsesApplications;

    public function __construct()
    {
        $this->pomodoros = new ArrayCollection();
        $this->clientUsesApplications = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTaskName(): ?string
    {
        return $this->task_name;
    }

    public function setTaskName(string $task_name): self
    {
        $this->task_name = $task_name;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getStimatedPomodoros(): ?int
    {
        return $this->stimated_pomodoros;
    }

    public function setStimatedPomodoros(int $stimated_pomodoros): self
    {
        $this->stimated_pomodoros = $stimated_pomodoros;

        return $this;
    }

    public function getActive(): ?bool
    {
        return $this->active;
    }

    public function setActive(bool $active): self
    {
        $this->active = $active;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getTaskState(): ?TaskState
    {
        return $this->task_state;
    }

    public function setTaskState(?TaskState $task_state): self
    {
        $this->task_state = $task_state;

        return $this;
    }

    /**
     * @return Collection|Pomodoro[]
     */
    public function getPomodoros(): Collection
    {
        return $this->pomodoros;
    }

    public function getPomodorosAmmount(): Int
    {
        return $this->pomodoros->count();
    }

    public function addPomodoro(Pomodoro $pomodoro): self
    {
        if (!$this->pomodoros->contains($pomodoro)) {
            $this->pomodoros[] = $pomodoro;
            $pomodoro->setTask($this);
        }

        return $this;
    }

    public function removePomodoro(Pomodoro $pomodoro): self
    {
        if ($this->pomodoros->contains($pomodoro)) {
            $this->pomodoros->removeElement($pomodoro);
            // set the owning side to null (unless already changed)
            if ($pomodoro->getTask() === $this) {
                $pomodoro->setTask(null);
            }
        }

        return $this;
    }

    public function getClock(): ?Clock
    {
        return $this->clock;
    }

    public function setClock(Clock $clock): self
    {
        $this->clock = $clock;

        // set the owning side of the relation if necessary
        if ($this !== $clock->getTask()) {
            $clock->setTask($this);
        }

        return $this;
    }

    /**
     * @return Collection|ClientUsesApplication[]
     */
    public function getClientUsesApplications(): Collection
    {
        return $this->clientUsesApplications;
    }

    public function addClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if (!$this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications[] = $clientUsesApplication;
            $clientUsesApplication->setTask($this);
        }

        return $this;
    }

    public function removeClientUsesApplication(ClientUsesApplication $clientUsesApplication): self
    {
        if ($this->clientUsesApplications->contains($clientUsesApplication)) {
            $this->clientUsesApplications->removeElement($clientUsesApplication);
            // set the owning side to null (unless already changed)
            if ($clientUsesApplication->getTask() === $this) {
                $clientUsesApplication->setTask(null);
            }
        }

        return $this;
    }

/*
 
    //////////////////////////////////////////////////////////////

*/
    public function getPomodorosOlderThan($aDate): Collection
    {
        return $this->getPomodoros()
            ->filter(function($pomo) use($aDate)
                {
                    return ($pomo->getEndingDate() < $aDate);
                });

    }


    public function getPomodorosNewerThan($aDate): Collection
    {
        return $this->getPomodoros()
            ->filter(function($pomo) use($aDate) 
                {
                    return ($pomo->getEndingDate() > $aDate);
                });
    }
 

/*
 
    //////////////////////////////////////////////////////////////

*/



}

src/Controller/MyTasksController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Common\EventManager;
use App\Entity\Task;
use App\Entity\Client;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\TaskState;
use App\Entity\Pomodoro;
use App\Entity\Clock;
use Symfony\Component\Validator\Constraints\Date;

class MyTasksController extends AbstractController
{
    /**
     * @Route("/my-tasks/{page}/{state}/{sort}", name="my_tasks",defaults={"page"=1, "state"="all", "sort"=0})
     */
    public function index(Request $request, $page, $state, $sort)
    {
        $entityManager = $this->getDoctrine()->getManager();

        $clientId = $this->get('security.token_storage')->getToken()->getUser()->getId();
        $pageLimit = 5;

        $filters = array('client' => $clientId);
        $orderBy = array();

        $state = strtoupper($state);
        if ($state != "ALL") {
            $stateObj = $entityManager->getRepository("App\Entity\TaskState")->findOneBy(['state' => $state]);
            $stateId = $stateObj->getId();
            $filters['task_state'] = $stateId;
        }
        switch ($sort) {
            case "name":
                $orderBy['task_name'] = "ASC";
                break;
            case "date":
                $orderBy['creation_date'] = "DESC";
                break;
            case "pomodoros":
                $orderBy['stimated_pomodoros'] = "DESC";
                break;
        }

        $countFilters = array('client' => $clientId);
        if ($state != "ALL") {
            $countFilters['task_state'] = $stateId;
        }
        /* var_dump($countFilters);*/
        /* var_dump($filters);*/

        $taskCount = $entityManager->getRepository('App\Entity\Task')->count($countFilters);
        $totalPages = ceil($taskCount / $pageLimit);

        $tasks = $entityManager->getRepository("App\Entity\Task")->findBy($filters, $orderBy, $pageLimit, ($page - 1) * $pageLimit);
        return $this->render('my_tasks/index.html.twig', [
            'controller_name' => 'MyTasksController',
            'tasks' => $tasks,
            'totalPages' => $totalPages,
            'currentPage' => $page
        ]);
    }

    /**
     * @param Task $task
     *
     * @Route("/{id}/start-task", requirements={"id" = "\d+"}, name="start_task_route")
     * @return RedirectResponse
     *
     */
    public function startTask(Task $task){

       $activeState = $this->getDoctrine()
        ->getRepository(TaskState::class)
        ->findOneByState('ACTIVE');

        $task->setTaskState($activeState);

        //Iniciando el reloj
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = new Clock($client,$task);
        $client->setClock($clock);

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($task);
        $entityManager->persist($clock);
        $entityManager->persist($client);
        $entityManager->flush();

        return $this->redirectToRoute('my_tasks');
    }


    /**
     * @param Task $task
     *
     * @Route("/{id}/stop-task", requirements={"id" = "\d+"}, name="stop_task_route")
     * @return RedirectResponse
     *
     */
    public function stopTask(Task $task){

        $entityManager = $this->getDoctrine()->getManager();

        /* Destruir el reloj sin guardar datos del ciclo actual */
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();

        /* Cambiar el estado de la tarea a pendiente */
        $pendingState = $this->getDoctrine()
        ->getRepository(TaskState::class)
        ->findOneByState('PENDING');
        $task->setTaskState($pendingState);
     

        $entityManager->persist($client);
        $entityManager->flush();

        $entityManager->persist($task);
        $entityManager->flush();

        $entityManager->remove($clock);
        $entityManager->flush();






        return $this->redirectToRoute('my_tasks');
    }

    /**
     * @param Task $task
     *
     * @Route("/{id}/finish-task", requirements={"id" = "\d+"}, name="finish_task_route")
     * @return RedirectResponse
     *
     */
    public function finishTask(Task $task){

        $entityManager = $this->getDoctrine()->getManager();

        /* Destruir el reloj sin guardar datos del ciclo actual */
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();

        /* Cambiar el estado de la tarea a terminada */
        $finishedState = $this->getDoctrine()
        ->getRepository(TaskState::class)
        ->findOneByState('FINISHED');
        $task->setTaskState($finishedState);
     
        $entityManager->persist($client);
        $entityManager->flush();

        $entityManager->persist($task);
        $entityManager->flush();

        $entityManager->remove($clock);
        $entityManager->flush();


        return $this->redirectToRoute('my_tasks');
    }


    /**
     *
     * @Route("/pause-task", name="pause_task_route")
     * @return RedirectResponse
     *
     */
    public function pauseTask(){

        $entityManager = $this->getDoctrine()->getManager();

        /* Pedir al reloj que se pause */
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();
        $clock->pause();

        $entityManager->persist($clock);
        $entityManager->flush();


        return $this->redirectToRoute('my_tasks');
    }

    /**
     *
     * @Route("/resume-task", name="resume_task_route")
     * @return RedirectResponse
     *
     */
    public function resumeTask(){

        $entityManager = $this->getDoctrine()->getManager();

        /* Pedir al reloj que se pause */
        
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();
        $clock->resume();

        $entityManager->persist($clock);
        $entityManager->flush();

        return $this->redirectToRoute('my_tasks');
    }

    /**
     *
     * @Route("/continue-task", name="continue_task_route")
     * @return RedirectResponse
     *
     */
    public function continueTask(){

        $entityManager = $this->getDoctrine()->getManager();

        
        
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();
        $clock->next();

        $entityManager->persist($clock);
        $entityManager->flush();

        return $this->redirectToRoute('my_tasks');
    }

    /**
     * @param Task $task
     *
     * @Route("/{id}/delete-task", requirements={"id" = "\d+"}, name="delete_task_route")
     * @return RedirectResponse
     *
     */
    public function deleteTask(Task $task){

        $entityManager = $this->getDoctrine()->getManager();
        $uses = $entityManager->getRepository('App\Entity\ClientUsesApplication')->findBy(['task'=>$task]);
        foreach ($uses as $use){
            $entityManager->remove($use);
        }
        $pomodoros = $entityManager->getRepository('App\Entity\Pomodoro')->findBy(['task'=>$task]);
        foreach ($pomodoros as $pomodoro){
            $entityManager->remove($pomodoro);
        }
        $clocks = $entityManager->getRepository('App\Entity\Clock')->findBy(['task'=>$task]);
        foreach ($clocks as $clock){
            $entityManager->remove($clock);
        }
        $entityManager->remove($task);
        $entityManager->flush();

        return $this->redirectToRoute('my_tasks');
    }

    /**
     *
     * @Route("/store", name="store_route")
     * @return RedirectResponse
     *
     */
    public function storeData(){

        $entityManager = $this->getDoctrine()->getManager();

        
        
        $client = $this->get('security.token_storage')->getToken()->getUser();
        $clock = $client->getClock();
        if (($clock->getPeriodType() == "Trabajo")&&($clock->getReady())) {
            $pomodoro = new Pomodoro();
            $pomodoro->setStartDate($clock->getPeriodStartStamp());
            $pomodoro->setEndingDate($clock->getDeadline());
            $pomodoro->setTask($clock->getTask());

            $clock->setReady(FALSE);


            $entityManager->persist($clock);
            $entityManager->flush();
            $entityManager->persist($pomodoro);
            $entityManager->flush();
        }
        return $this->redirectToRoute('my_tasks');
    }

}

templates/my_tasks/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} Mis Tareas {% endblock %}

{% block body %}
    <div class="container my-tasks-form-container d-flex justify-content-center align-items-center">
        <div class="row">
            <div class="position-relative shadow bg-white border-top col-md-12 my-tasks-box">
                <h2 class="text-center font-weight-light"> Mis Tareas </h2>
                <div class="my-3 my-tasks-filter-bar">
                    {% set state = app.request.attributes.get('state') %}
                    {% set sort = app.request.attributes.get('sort') %}
                    {% set page = app.request.attributes.get('page') %}
                    {#{{ path('my_tasks', {'state':state,'sort':"name"}#}

                    <a href="{{ path('my_tasks') }}" class="my-tasks-filter {% if state == 'all' %} active {% endif %}">Todas</a>
                    <a href="{{ path('my_tasks', {'state':"pending"}) }}"
                       class="my-tasks-filter {% if state == 'pending' %} active {% endif %}">Pendientes</a>
                    <a href="{{ path('my_tasks', {'state':"finished"}) }}"
                       class="my-tasks-filter {% if state == 'finished' %} active {% endif %}">Finalizadas</a>
                    <select id="select-sort" class="custom-select my-tasks-select-sort">
                        <option selected disabled hidden value="order_by"> Ordenar por</option>
                        <option data-sorted-url="{{ path('my_tasks', {'state':state,'sort':"name"}) }}" value="name">
                            Nombre (a-z)
                        </option>
                        <option data-sorted-url="{{ path('my_tasks', {'state':state,'sort':"date"}) }}" value="date">
                            Fecha de creación (más reciente)
                        </option>
                        <option data-sorted-url="{{ path('my_tasks', {'state':state,'sort':"pomodoros"}) }}"
                                value="pomodoros"> Cantidad de pomodoros (mayor cantidad)
                        </option>
                    </select>
                    <a href="{{ path('task_creation') }}">
                        <button type="button" class="btn btn-danger my-tasks-create-task-button">Crear tarea</button>
                    </a>

                </div>
                {% if tasks is defined %}
                    <div class="my-tasks-task-section">
                        {% for task in tasks %}
                            <div class="my-tasks-task-container my-3">
                                <span class="my-tasks-task-name"
                                      title="{{ task.taskName }}">{{ task.taskName }}</span>
                                <span class="my-tasks-pomodoros"
                                      title="Pomodoros usados/estimados"> {{ task.pomodorosAmmount() }}
                                    /{{ task.stimatedPomodoros }} </span>

                                {% if task.taskState.state == "PENDING" %}
                                    <span class="my-tasks-task-state" title="Estado de la tarea"> Pendiente </span>
                                {% endif %}
                                {% if task.taskState.state == "ACTIVE" %}
                                    {% if app.user.clock.isPaused() %}
                                        <span class="my-tasks-task-state" title="Estado de la tarea"> Pausado </span>
                                    {% else %}
                                        <span class="my-tasks-task-state" title="Estado de la tarea"> Activo </span>
                                    {% endif %}
                                {% endif %}

                                {% if task.taskState.state == "FINISHED" %}
                                    <span class="my-tasks-task-state" title="Estado de la tarea"> Finalizado </span>
                                {% endif %}
                                <span title="Fecha de creación"> {{ task.creationDate | date("m/d/Y") }} </span>


                                <div class="my-tasks-action-buttons-container d-flex justify-content-end">

                                    {% if task.taskState.state == "PENDING" %}
                                        {% if app.user.clock is null  %}
                                            <a href="{{ path('start_task_route', {'id': task.id }) }}" title="Iniciar tarea"><img
                                                        src="/build/assets/img/buttons/play.svg"
                                                        class="my-tasks-action-button mr-2"></a>
                                        {% endif %}
                                    {% endif %}
                                    {% if task.taskState.state == "ACTIVE" %}
                                        {% if task.clock.canBePaused() %}
                                            <a href="{{ path('pause_task_route', {}) }}" title="Pausar tarea">
                                            <img src="/build/assets/img/buttons/pause.svg" class="my-tasks-action-button mr-2">
                                            </a>
                                        {% elseif task.clock.canBeResumed() %}
                                            <a href="{{ path('resume_task_route', {}) }}" title="Continuar tarea">
                                            <img src="/build/assets/img/buttons/play.svg" class="my-tasks-action-button mr-2">
                                            </a>
                                        {% elseif task.clock.canDoNext() %}
                                            <a href="{{ path('continue_task_route', {}) }}" title="Continuar con el siguiente periodo">
                                            <img src="/build/assets/img/buttons/skip.png" class="my-tasks-action-button mr-2">
                                            </a>                                            
                                        {% endif %}
                                        <a href="{{ path('finish_task_route', {'id': app.user.clock.task.getId() }) }}" title="Finalizar tarea"><img
                                                    src="/build/assets/img/buttons/success.png"
                                                    class="my-tasks-action-button mr-2"></a>
                                        <a href="{{ path('stop_task_route', {'id': task.id }) }}" title="Detener tarea"><img
                                                    src="/build/assets/img/buttons/stop.png"
                                                    class="my-tasks-action-button mr-2"></a>
                                    {% endif %}
                                    <a href="{{ path('delete_task_route',{'id': task.id }) }}" title="Borrar tarea"><img src="/build/assets/img/buttons/trash.png"
                                                                          class="my-tasks-action-button mr-2"></a>
                                </div>
                            </div>
                        {% else %}
                            <div class="my-tasks-empty-message">No hay tareas por aquí.</div>
                        {% endfor %}
                    </div>
                {% endif %}

                {% if totalPages > 0 %}
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if currentPage == 1 %} disabled {% endif %}">
                            <a class="page-link"
                               href="{{ path('my_tasks', {'sort':sort, 'page': currentPage-1, state: state}) }}">Anterior</a>
                        </li>
                        {% for i in 1..totalPages %}
                            <li class="page-item {% if currentPage == i %} active {% endif %}">
                                <a class="page-link"
                                   href="{{ path('my_tasks', {'sort':sort, 'page': i, state: state}) }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        <li class="page-item  {% if currentPage == totalPages %} disabled {% endif %}">
                            <a class="page-link"
                               href="{{ path('my_tasks', {'sort':sort, 'page': currentPage+1, state: state}) }}">Siguiente</a>
                        </li>
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    <script>
        document.getElementById("select-sort").onchange = function (e) {
            if (e.target.value !== "order_by") {
                var url = e.target.selectedOptions[0].getAttribute('data-sorted-url');
                localStorage['selected_task_sort'] = document.getElementById("select-sort").value;
                window.location = url;
            }
        };

        window.onload = function () {
            if (localStorage['selected_task_sort'])
                document.getElementById("select-sort").value = localStorage['selected_task_sort'];
        }
    </script>
{% endblock %}